ARG UBUNTU_VER=22.04
FROM ubuntu:${UBUNTU_VER} as demo

ENV LANG C.UTF-8
ENV http_proxy http://proxy-dmz.intel.com:911
ENV https_proxy http://proxy-dmz.intel.com:912
ENV no_proxy localhost,127.0.0.1,*.intel.com

SHELL ["/bin/bash", "--login", "-c"]

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
    autoconf \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    numactl \
    time \
    wget \
    && rm -rf /var/lib/apt/lists/*

ENV PATH /opt/miniconda3/bin:$PATH

WORKDIR /app

COPY api.py adapter.py convert.py model_worker.py utils.py ./
COPY llm_metrics.py llm_metrics.py

# KMP
ENV KMP_BLOCKTIME=1
ENV KMP_SETTINGS=1
ENV KMP_AFFINITY=granularity=fine,compact,1,0
# OMP
ENV OMP_NUM_THREADS=30

CMD ["numactl", "-C", "120-149", "-m", "0", "conda", "run", "--no-capture-output", "-n", "llmenv", "python", "api.py"]
